### ISSUE TITLE
Possible error in Service Providers / Boot code example

### ISSUE THREAD

**Issue by matt416** [Rareloop/lumberjack-docs#8]
In the code example for **Boot** at https://docs.lumberjack.rareloop.com/container/service-providers

I believe that `use Rareloop\Lumberjack\Facades\Config;`

should be `use Rareloop\Lumberjack\Config;`

If you use the facade, you get an undefined method exception, Rareloop\Lumberjack\Facades\Config::get()

**Comment by adamtomat** [comment]
Thanks, I'll take a look 👌

**Comment by adamtomat** [comment]
Indeed this is a typo, thanks for reporting it @matt416. Should be fixed now.
